title: Way
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1875
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#000000'
    - '#2F2F2F'
    - '#FFFFFF'
    - '#777777'
    - '#A2A2A2'
  rhythmicContrast: 0.5311493
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Wayraps
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1208378
layout_spectrum: 1
