layout_spectrum: 1
color:
  saturation: 1
  lightness: 0
  brandStrength: 1
  brandColors:
    - '#000000'
    - '#2F2F2F'
    - '#FFFFFF'
    - '#777777'
    - '#A2A2A2'
  rhythmicContrast: 0.556928
typography_spectrum: 0.4774436
name: Wayraps
