name: Wayraps
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4774436
title: Way
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2F2F2F'
    - '#FFFFFF'
    - '#777777'
    - '#A2A2A2'
  brandStrength: 1
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
